# Generated by Django 3.2.7 on 2021-09-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApp', '0004_auto_20210909_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='company_phone_number_db',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='customer_phone_number_db',
            field=models.IntegerField(),
        ),
    ]
