# Generated by Django 3.2.7 on 2021-09-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApp', '0005_auto_20210909_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
