# Generated by Django 3.2.7 on 2021-09-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApp', '0006_transactions_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='name',
        ),
    ]
